# Generated by Django 2.2.7 on 2019-11-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_activity_userinvolvedactivity'),
        ('expenses', '0003_ledger'),
    ]

    operations = [
    ]
