# Generated by Django 2.2.7 on 2019-11-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20191114_1944'),
        ('expenses', '0004_merge_20191115_1020'),
    ]

    operations = [
    ]
