# Generated by Django 2.2.7 on 2019-11-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_merge_20191115_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='expenses.Expense'),
        ),
    ]
