# Generated by Django 2.2.7 on 2019-11-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_ledger_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='expenses.Expense'),
        ),
    ]
