# Generated by Django 2.2.7 on 2019-11-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20191115_1530'),
        ('expenses', '0005_merge_20191115_1117'),
    ]

    operations = [
    ]
