# Generated by Django 2.2.7 on 2019-11-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_merge_20191116_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='model_name',
            field=models.CharField(default='Expense', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvolvedactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='expenses.Activity'),
        ),
    ]
