# Generated by Django 2.2.7 on 2019-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20191116_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
